# Generated by Django 3.0.6 on 2020-05-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200528_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='logo',
            field=models.ImageField(default='D:\\iPC\\WebProject\\queuemgmt\\media/logos/default.png', upload_to='logos'),
        ),
    ]
