# Generated by Django 3.0.6 on 2020-05-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20200528_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='logo',
            field=models.ImageField(default='mainapp/media/logos/default.png', upload_to='mainapp/media/logos'),
        ),
    ]
