# Generated by Django 3.0.6 on 2020-05-28 10:30

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20200528_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='logo',
            field=models.ImageField(default='mainapp/media/logos/default.png', upload_to=mainapp.models.get_upload_path),
        ),
    ]
