# Generated by Django 3.0.6 on 2020-05-28 10:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20200528_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_date', models.DateTimeField(verbose_name='datetime queue')),
                ('phone_number', models.CharField(blank=True, max_length=12)),
                ('token_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('status', models.IntegerField(choices=[(0, 'Queue'), (1, 'Cancel'), (2, 'Oncall'), (3, 'Serving'), (4, 'Success')])),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.Shop')),
            ],
        ),
    ]
